[build]
  command = "npm install && npm run build"
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  framework = "#static"
  targetPort = 3000
  publish = "public"
  functions = "netlify/functions"
